% Visualize and validate the binary output generated by poisson_solver3d.c.
%
% The parameters below must match the values used when running the solver.

close all;
clear;

%% Problem parameters

m = 100;
n = 20;
q = 10;

ax = 0;
ay = 0;
az = 0;

h = 0.1;

result_file = 'results';

%% Read numerical solution

fileID = fopen(result_file, 'r');

if fileID == -1
    error('Could not open result file: %s', result_file);
end

data = fread(fileID, 'double');
fclose(fileID);

expected_entries = m * n * q;

if numel(data) ~= expected_entries
    error(['Unexpected number of entries in result file. ', ...
           'Expected %d values, got %d.'], expected_entries, numel(data));
end

% The solver writes the data in C ordering. The reshape/permute combination
% converts the binary output into an array compatible with MATLAB/Octave's
% column-major memory layout and meshgrid convention.
u_num = permute(reshape(data, [q, n, m]), [2, 3, 1]);

%% Create grid

bx = ax + m*h;
by = ay + n*h;
bz = az + q*h;

xv = ax + h*(1:m);
yv = ay + h*(1:n);
zv = az + h*(1:q);

[x, y, z] = meshgrid(xv, yv, zv);

%% Analytical reference solution

u_exact = (1 + x + z) .* sin(x + y);

relative_error = abs(u_exact - u_num) ./ max(abs(u_exact), eps);

%% Slice positions for visualization

xslice = xv(round(linspace(1, m, min(3, m))));
yslice = yv(end);
zslice = zv(round(linspace(1, q, min(3, q))));

%% Plot numerical solution

figure;
h_slice = slice(x, y, z, u_num, xslice, yslice, zslice);
set(h_slice, 'EdgeColor', 'none');
title('Numerical solution');
xlabel('x');
ylabel('y');
zlabel('z');
colorbar;

%% Plot analytical solution

figure;
h_slice = slice(x, y, z, u_exact, xslice, yslice, zslice);
set(h_slice, 'EdgeColor', 'none');
title('Analytical solution');
xlabel('x');
ylabel('y');
zlabel('z');
colorbar;

%% Plot relative error

figure;
h_slice = slice(x, y, z, relative_error, xslice, yslice, zslice);
set(h_slice, 'EdgeColor', 'none');
title('Relative error');
xlabel('x');
ylabel('y');
zlabel('z');
colorbar;
